### ISSUE TITLE
Failed to load the koala package

### ISSUE THREAD

**Issue by Leeds-eBooks** [Ff00ff/koala-atom-package#3]
[Enter steps to reproduce below:]
1. Launch atom, either from terminal or with a click

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [koala](https://github.com/ff00ff/koala-atom-package) package, v0.6.0
### Stack Trace

Failed to load the koala package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/ben/Dropbox/Software/.atom/packages/koala/lib/auth-view.js:3:197)
    at /Users/ben/Dropbox/Software/.atom/packages/koala/lib/auth-view.js:10:3
    at Object.<anonymous> (/Users/ben/Dropbox/Software/.atom/packages/koala/lib/auth-view.js:146:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/ben/Dropbox/Software/.atom/packages/koala/lib/koala.js:3:16)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "remember-session",
      "emmet",
      "symbols-view",
      "ask-stack",
      "save-session",
      "word-jumper",
      "atom-beautify",
      "language-babel"
    ],
    "themes": [
      "seti-ui",
      "kingfisher-syntax"
    ]
  },
  "koala": {
    "accessToken": "e50024cad4d196cfc469083f5ea9ec32b713e239b5848999e73fa6ea36270cfcbff3cc73edab68b5668b44abfa37c5b185a494183530972fac2669d7ff838114805f0fce545c53120b17b08a1d38e04abdfcff0d6eb6d1ace1f32e07b103d989becb7495b94c057f4285b1369180f9db7d6b1f55899bce33419f90a386201c9c",
    "email": "enquiries@leeds-ebooks.co.uk"
  }
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.9
atom-ctags, v4.1.1
color-picker, v2.0.4
docblockr, v0.7.2
fold-functions, v0.2.0
git-log, v0.4.1
highlight-selected, v0.9.3
javascript-snippets, v1.0.0
jsformat, v0.9.0
kingfisher-syntax, v0.1.9
koala, v0.6.0
language-liquid, v0.2.0
language-scala, v1.1.2
linter, v0.12.6
linter-coffeelint, v0.3.1
linter-csslint, v0.0.13
linter-jshint, v0.1.6
linter-jsonlint, v0.1.4
linter-scalac, v0.3.4
linter-scss-lint, v1.0.4
minimap, v4.9.4
pretty-json, v0.3.3
project-manager, v1.15.8
raml, v0.1.0
seti-ui, v0.7.1
trailing-spaces, v0.3.0

# Dev
No dev packages
```

**Comment by ffsantos92** [comment]
@Leeds-eBooks This repo seems dead. [http://wakatime.com/](WakaTime) is a great alternative :+1:
